amcgh_django/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from CustomAdminPanel import views, HODview

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('homepage.urls')),
                  path('login/', views.showLoginPage, name="login"),
                  path('doLogin/', views.doLogin, name="doLogin"),
                  # path('get_user_details/', views.GetUserDetails, name="GetUserDetails"),
                  path('logout_user/', views.logout_user, name="logout"),
                  path('admin_home/', HODview.admin_home, name="admin_home"),

                  path('add_department/', HODview.add_department, name="add_department"),
                  path('add_department_save/', HODview.add_department_save, name="add_department_save"),

                  path('add_service/', HODview.add_service, name="add_service"),
                  path('add_service_save/', HODview.add_service_save, name="add_service_save"),

                  path('add_doctor', HODview.add_doctor, name="add_doctor"),
                  path('add_doctor_save', HODview.add_doctor_save, name="add_doctor_save"),

                  path('add_mt', HODview.add_mt, name="add_mt"),
                  path('add_mt_save', HODview.add_mt_save, name="add_mt_save"),

                  path('add_gb', HODview.add_gb, name="add_gb"),
                  path('add_gb_save', HODview.add_gb_save, name="add_gb_save"),

                  path('add_gallery', HODview.add_gallery, name="add_gallery"),
                  path('add_gallery_save', HODview.add_gallery_save, name="add_gallery_save"),

                  path('add_category', HODview.add_category, name="add_category"),
                  path('add_category_save', HODview.add_category_save, name="add_category_save"),


                  path('manage_doctor', HODview.manage_doctor, name="manage_doctor"),
                  path('manage_service', HODview.manage_service, name="manage_service"),
                  path('manage_department', HODview.manage_department, name="manage_department"),
                  path('manage_mt', HODview.manage_mt, name="manage_mt"),
                  path('manage_gb', HODview.manage_gb, name="manage_gb"),
                  path('manage_gallery', HODview.manage_gallery, name="manage_gallery"),


                  path('edit_mt/<str:mt_id>', HODview.edit_mt, name="edit_mt"),
                  path('edit_mt_save', HODview.edit_mt_save, name="edit_mt_save"),
                  path('edit_gb/<str:gb_id>', HODview.edit_gb, name="edit_gb"),
                  path('edit_gb_save', HODview.edit_gb_save, name="edit_gb_save"),
                  path('edit_doctor/<str:doctor_id>', HODview.edit_doctor, name="edit_doctor"),
                  path('edit_doctor_save', HODview.edit_doctor_save, name="edit_doctor_save"),
                  path('edit_department/<str:department_id>', HODview.edit_department, name="edit_department"),
                  path('edit_gallery/<str:gallery_id>', HODview.edit_gallery, name="edit_gallery"),
                  path('edit_department_save', HODview.edit_department_save, name="edit_department_save"),
                  path('edit_gallery_save', HODview.edit_gallery_save, name="edit_gallery_save"),

                  # # #     Staff URL Path
                  # path('staff_home', Staffviews.staff_home, name="staff_home"),
                  # path('staff_take_attendence', Staffviews.staff_take_attendence, name="staff_take_attendence"),
                  # path('student_home', Studentviews.student_home, name="student_home")
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL,
                                                                                         document_root=settings.STATIC_ROOT)

homepage/urls.py
from django.conf.urls.static import static

from django.conf import settings
from homepage.views import (home_view,
                            blog_view,
                            about_us_view,
                            service_list_view,
                            doctor_list_view,
                            contact_view,
                            doctor_details,
                            gb_list_view,
                            department_details,
                            management_team_view,
                            service_details_view,
                            gallery_view,backgroundhistory,career,whoweare,missionvission)
from django.urls import path
from . import views

app_name = 'homepage'
urlpatterns = [
                  path('', home_view, name='Home'),
                  # path('department_view/',department_view, name='department'),
                  # path('service/',service_view,name='service'),
                  # path('appointment/', appointment_view, name= 'appointment'),
                  path('contact/', contact_view, name='contact-us'),
                  path('blog/', blog_view, name='blog'),
                  path('about/', about_us_view, name='about'),
                  path('gallery/', gallery_view, name='gallery'),
                  # path('login_user/', views.user_login, name='login'),
                  path('register_user', views.register_view, name='register'),
                  path('service_details/<int:id>', service_details_view, name='service_detail'),
                  path('service-list/', service_list_view, name='service-list'),
                  # path('service-insert/', service_insert_view),
                  # path('news/', views.blog_list_view, name='news'),
                  # path('<int:id>/', views.dynamic_lookup_view, name='news-details'),
                  path('doctor-list/', doctor_list_view, name='doctor-list'),
                  path('department_details/<int:id>/', department_details, name='department_details'),
                  # path('department-list/', department_list_view, name='department-list'),
                  path('doctor_details/<int:id>', doctor_details, name="doctor_details"),
                  path('gb_list/', gb_list_view, name="governing-body"),
                  path('mt_list/', management_team_view, name="management-team"),
                  path('career/', career, name="career"),
                  path('mission&vission/', missionvission, name="mission&vission"),
                  path('whoWeAre/', whoweare, name="whoWeAre"),
                  path('backgroundHistory/', backgroundhistory, name="backgroundHistory"),

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL,
                                                                                         document_root=settings.STATIC_ROOT)

homepage/models.py
# from datetime import datetime
# from django.db import models
# from django.urls import reverse
# from PIL import Image
# from ckeditor.fields import RichTextField
#
#
# class Degree(models.Model):
#     degree_name = models.CharField(max_length=50, null=False)
#
#     def __str__(self):
#         return self.degree_name
#
#
# class Department(models.Model):
#     name = models.CharField(max_length=50)
#     department_image = models.ImageField(upload_to='department_image', default='default.png')
#     short_description = models.CharField(max_length=250, default='Nothing Found')
#     description = models.TextField(blank=False, default='Nothing Found')
#     published = models.DateTimeField(default=datetime.now)
#
#     def __str__(self):
#         return self.name
#
#     def save(self, **kwargs):
#         super().save()
#
#         img = Image.open(self.department_image.path)
#         if img.height > 300 or img.width > 300:
#             output_size = (300, 300)
#             img.thumbnail(output_size)
#             img.save(self.department_image.path)
#
#     def get_absolute_url(self):
#         return reverse("Doctor:department-detail", kwargs={"id": self.id})
#
#
# class Doctor(models.Model):
#     title = models.CharField(max_length=100, blank=False)
#     Designation = models.CharField(blank=False, null=True, max_length=100)
#     doctor_image = models.ImageField(upload_to='doctor_profile_image', default='default.png')
#     Degree = models.ManyToManyField(Degree, blank=False)
#     contact = models.EmailField(max_length=254, blank=False)
#     department = models.ForeignKey(Department, blank=False, null=False, on_delete=models.CASCADE)
#     research_publications = RichTextField(blank=True, null=True)
#     visiting_time = models.CharField(max_length=254, blank=False)
#     published = models.DateTimeField(default=datetime.now)
#
#     def save(self, **kwargs):
#         super().save()
#
#         img = Image.open(self.doctor_image.path)
#         if img.height > 300 or img.width > 300:
#             output_size = (300, 300)
#             img.thumbnail(output_size)
#             img.save(self.doctor_image.path)
#
#     def __str__(self):
#         return self.title
#
#
# # Create your models here.
# class Author(models.Model):
#     name = models.CharField(max_length=30)
#
#     def __str__(self):
#         return self.name
#
#
# class Category(models.Model):
#     name = models.CharField(max_length=20)
#
#     def __str__(self):
#         return self.name
#
#
# class news(models.Model):
#     title = models.CharField(max_length=120)
#     news_image = models.ImageField(upload_to="Newsevents", default='default.png')
#     author = models.ForeignKey(Author, on_delete=models.CASCADE)
#     description = RichTextField(default='No Information Available', blank=False, null=False)
#     categories = models.ManyToManyField(Category)
#     publish_date = models.DateTimeField()
#     views = models.IntegerField(default=0)
#     reviewed = models.BooleanField(default=False)
#
#     def __str__(self):
#         return self.title
#
#     def get_absolute_url(self):
#         return reverse("Newsevents:news-details", kwargs={"id": self.id})
#
#
# class service(models.Model):
#     service_name = models.CharField(max_length=50)
#     service_short_description = models.CharField(max_length=500)
#     service_description = models.TextField(blank=False, null=False)
#     service_image = models.ImageField(upload_to='Service', default='medical_oncology.jpg')
#
#     def get_absolute_url(self):
#         return reverse("Service:service-detail", kwargs={"id": self.id})  # /* dynamic url */
#
#     def __str__(self):
#         return self.service_name

homepage/forms.py
# from django import forms
# from .models import Department, service
# from .models import Doctor
#
# class DoctorForm(forms.ModelForm):
#
#     contact = forms.EmailField()
#
#     class Meta:
#         model = Doctor
#         fields = [
#             'title',
#             'Degree',
#             'Designation',
#             'contact',
#             'department'
#         ]
#
#
# class ServiceForm(forms.ModelForm):
#     class Meta:
#         model = service
#         fields = [
#             'service_name',
#             'service_short_description',
#             'service_description',
#             'service_image'
#         ]
#
#
#
#
# class DepartmentForm(forms.ModelForm):
#
#     class Meta:
#         model= Department
#         fields= [
#             'name',
#             'description',
#             'department_image'
#         ]
#

homepage/views.py
from django.shortcuts import render
from CustomAdminPanel.models import Doctors, Departments, Service, GoverningBody, ManagementTeam, Gallery, \
    GalleryCategory

from django.db.models import Q


def home_view(request):
    department_menu = Departments.objects.all()
    department_home_view = Departments.objects.all()[:2]
    service_home_view = Service.objects.all()[:8]
    doctor_list = Doctors.objects.all()
    context = {
        'service_list': service_home_view,
        'doctor_list': doctor_list,
        'department_list': department_home_view,
        'department_menu': department_menu
    }
    return render(request, 'homepage/index.html', context)


def blog_view(request):
    department_menu = Departments.objects.all()
    context = {
        'department_menu': department_menu
    }
    return render(request, 'News&events/blog-sidebar.html', context)


def about_us_view(request):
    department_menu = Departments.objects.all()
    context = {
        'department_menu': department_menu
    }
    return render(request, 'about.html', context)


def register_view(request):
    department_menu = Departments.objects.all()
    context = {
        'department_menu': department_menu
    }
    return render(request, 'User/register.html', context)


# def doctor_form_view(request):
#     form= DoctorForm()
#     if request.method == "POST":
#         form= DoctorForm(request.POST)
#         if form.is_valid():
#             form.save()
#             return redirect('doctor-insert')
#         else:
#             form = DoctorForm()
#
#     context = {
#         'form': form
#         }
#     return render(request, "Doctors/doc_insert.html", context)


def doctor_details(request, id):
    request.session['doctor_id'] = id
    obj = Doctors.objects.get(admin=id)
    doctor_details = Doctors.objects.all()
    department_menu = Departments.objects.all()
    context = {
        'object': obj,
        'doctor_details': doctor_details,
        'department_menu': department_menu
    }
    return render(request, "Doctors/doctor-single.html", context)


def department_details(request, id):
    request.session['department_id'] = id
    department = Departments.objects.get(id=id)
    doctor_list = Doctors.objects.all()
    department_menu = Departments.objects.all()
    department_list = Departments.objects.all()
    departments = request.GET.get('departments')
    if departments is None:
        pass
    else:
        doctor_list = Doctors.objects.filter(department_id__department_name__icontains=departments)

    context = {
        'doctor_list': doctor_list,
        'department': department,
        'department_list': department_list,
        "id": id,
        'department_menu': department_menu
    }
    return render(request, "Department/department-single.html", context)


def is_valid_queryparam(param):
    return param != '' and param is not None


def doctor_list_view(request, *args, **kwargs):
    department_menu = Departments.objects.all()
    qs = Doctors.objects.all()

    department_list = Departments.objects.values_list('department_name', flat=True)

    name_contains_query = request.GET.get('name_contains')
    print(name_contains_query)

    if is_valid_queryparam(name_contains_query):
        qs = qs.filter(department_id__department_name__contains=name_contains_query)
    else:
        qs = Doctors.objects.all()

    context = {
        'queryset': qs,
        'department_list': department_list,
        'department_menu': department_menu

    }

    return render(request, "Doctors/doctor_list.html", context)


def service_list_view(request):
    department_menu = Departments.objects.all()
    if 'q' in request.GET:
        q = request.GET['q']
        filtered_service_list = Service.objects.filter(service_name__icontains=q)
    else:
        filtered_service_list = Service.objects.all()

    context = {
        's_list': filtered_service_list,
        'department_menu': department_menu
    }
    return render(request, "Services/service.html", context)


def gb_list_view(request):
    department_menu = Departments.objects.all()
    gb = GoverningBody.objects.all()

    context = {
        'gb': gb,
        'department_menu': department_menu
    }
    return render(request, "governing_body.html", context)


def management_team_view(request):
    management_team = ManagementTeam.objects.all()
    department_menu = Departments.objects.all()
    context = {
        'management_team': management_team,
        'department_menu': department_menu
    }
    return render(request, "management_team.html", context)


def service_details_view(request, id):
    service = Service.objects.get(id=id)
    service_details = Service.objects.all()
    department_menu = Departments.objects.all()
    context = {
        'service': service,
        'service_details': service_details,
        'department_menu': department_menu
    }
    return render(request, "Services/service-detail.html", context)


def contact_view(request):
    department_menu = Departments.objects.all()
    context = {
        'department_menu': department_menu
    }
    return render(request, 'contact.html', context)


def gallery_view(request):
    department_menu = Departments.objects.all()
    gallery_category = GalleryCategory.objects.all()
    gallery = Gallery.objects.all()
    filterd_gallery_category = request.GET.get('category')

    if filterd_gallery_category == 'All':
        gallery = Gallery.objects.all()
    elif is_valid_queryparam(filterd_gallery_category):
        gallery = gallery.filter(category_id__category_name=filterd_gallery_category)

    context = {
        'gallery_category': gallery_category,
        'filterd_gallery': gallery,
        'department_menu': department_menu
    }
    return render(request, 'gallary.html', context)


def career(request):
    return render(request, 'career.html')


def missionvission(request):
    return render(request, 'mission&vision.html')


def whoweare(request):
    return render(request, 'whoweare.html')


def backgroundhistory(request):
    return render(request, 'backgroundhistory.html')

homepage/templates/Services/service-detail.html
{% extends 'base.html' %}
{% block title %}{{ service.service_name }} | Ahsania Mission Cancer & General Hospital{% endblock title %}
{% block page_name %}All Services{% endblock page_name %}
{% block page_link %}<a href="{% url 'homepage:service-list' %}">Service</a>{% endblock page_link %}
{% block page_link_1 %}<a href="{{ service.get_absolute_url }}">{{ service.service_name }}</a>{% endblock page_link_1 %}
{% load static %}
{% block content %}
        <!-- Start Service -->
        <section class="section-padding bg-light-white service-page">
            <div class="container">
                <div class="row">
                    <aside class="col-lg-4">
                        <div class="sidebar_wrap mb-md-80">
                            <div class="sidebar">
                                <div class="sidebar_widgets mb-xl-30">
                                    <div class="widget_title bg-light-blue">
                                        <h5 class="no-margin text-custom-white fw-600">Search</h5>
                                    </div>
                                    <form>
                                        <div class="form-group mb-0">
                                            <div class="search p-relative">
                                                <input type="text" name="#" class="form-control form-control-custom" placeholder="Title or keywords">
                                            </div>
                                        </div>
                                    </form>
                                </div>
                               <div class="sidebar_widgets mb-xl-30">
                                    <div class="widget_title bg-light-blue">
                                        <h5 class="no-margin text-custom-white fw-600">Genmed Services</h5>
                                    </div>
                                    <ul class="custom sidebar-services">
                                        <li class="active">
                                            <a href="service-detail.html" class="text-custom-black fs-14">{{ service.service_name }} <span><i class="fas fa-chevron-right"></i></span></a>
                                        </li>
                                        {% for service in service_details %}
                                        <li>
                                            <a href="{{ service.get_absolute_url }}" class="text-custom-black fs-14">{{ service.service_name }}<span><i class="fas fa-chevron-right"></i></span></a>
                                        </li>
                                        {% endfor %}

                                    </ul>
                                </div>
                                <div class="sidebar_widgets mb-xl-30">
                                    <div class="widget_title bg-light-blue">
                                        <h5 class="no-margin text-custom-white fw-600">Opening Hours</h5>
                                    </div>
                                    <table class="table text-custom-black">
                                        <tbody>
                                            <tr>
                                                <td>Mon – Wed</td>
                                                <td> - </td>
                                                <td class="text-right">9:00 AM - 7:00 PM</td>
                                            </tr>
                                            <tr>
                                                <td>Thursday</td>
                                                <td> - </td>
                                                <td class="text-right">9:00 AM - 6:30 PM</td>
                                            </tr>
                                             <tr>
                                                <td>Friday</td>
                                                <td> - </td>
                                                <td class="text-right">9:00 AM - 6:00 PM</td>
                                            </tr>
                                            <tr class="last-tr">
                                                <td>Sun - Sun</td>
                                                <td>-</td>
                                                <td class="text-right">CLOSED</td>
                                             </tr>
                                          </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </aside>

                   <div class="col-lg-8">
                        <div class="col-12">
                            <div class="service-detail-sec bg-custom-white bx-wrapper">
                                <div class="services-detail-slider mb-xl-30">
                                    <div class="service-image">
                                        <img src="{{ service.service_image }}" class="image-fit" alt="img">
                                        <div class="overlay overlay-bg-black"></div>
                                        <div class="service-text-wrapper transform-center">
                                            <h3 class="text-custom-white">{{ service.service_name }}</h3>
                                        </div>
                                    </div>

                                </div>
                                <div class="service-meta mb-xl-30">
                                    <h2 class="text-custom-black fw-600">{{ service.service_name}}</h2>
                                    <p class="text-light-white">{{ service.service_description|safe }}</p>
                                                 </div>
                            </div>

                    </div>
                </div>
                </div>
                </div>
        </section>
        <!-- End Service -->

{% endblock %}

homepage/templates/Services/service-insert.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

    <section class="appoinment section">
  <div class="container">
    <div class="row">
      <div class="col-lg-4">
          <div class="mt-3">
            <div class="feature-icon mb-3">
              <i class="icofont-support text-lg"></i>
            </div>
             <span class="h3">Call for an Emergency Service!</span>
              <h2 class="text-color mt-3">+84 789 1256 </h2>
          </div>
      </div>

      <div class="col-lg-8">
           <div class="appoinment-wrap mt-5 mt-lg-0 pl-lg-5">
            <h2 class="mb-2 title-color">Add Service</h2>
               <form id="#" class="ServiceForm" method="POST" enctype="multipart/form-data" action="">
                   {% csrf_token %}
                    {{ form.as_p }}
                <button type="submit">Upload</button>
                </form>
            </div>
        </div>
      </div>
    </div>
  </div>

</section>

{% endblock %}

homepage/templates/Services/service-single.html
{% extends 'base.html' %}

{% load static %}

{% block content %}

<section class="page-title bg-1">
  <div class="overlay"></div>
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class="block text-center">
          <span class="text-white">Service Details</span>
            <h1 class="text-capitalize mb-5 text-lg">{{ object.service_name }}</h1>
        </div>
      </div>
    </div>
  </div>
</section>


<section class="section department-single">
	<div class="container">
		<div class="row">
			<div class="col-lg-12">
				<div class="department-img">
					<img src="{{ object.service_image.url }}" alt="" class="img-fluid">
				</div>
			</div>
		</div>

		<div class="row">
			<div class="col-lg-8">
				<div class="department-content mt-5">
					<h3 class="text-md">{{ object.service_name }}</h3>
					<div class="divider my-4"></div>
					<p class="lead">{{ object.service_description }}</p>


					<h3 class="mt-5 mb-4">Services features</h3>
					<div class="divider my-4"></div>
					<ul class="list-unstyled department-service">
						<li><i class="icofont-check mr-2"></i>International Drug Database</li>
						<li><i class="icofont-check mr-2"></i>Stretchers and Stretcher Accessories</li>
						<li><i class="icofont-check mr-2"></i>Cushions and Mattresses</li>
						<li><i class="icofont-check mr-2"></i>Cholesterol and lipid tests</li>
						<li><i class="icofont-check mr-2"></i>Critical Care Medicine Specialists</li>
						<li><i class="icofont-check mr-2"></i>Emergency Assistance</li>
					</ul>

					<a href="#" class="btn btn-main-2 btn-round-full">Make an Appoinment<i class="icofont-simple-right ml-2  "></i></a>
				</div>
			</div>

			<div class="col-lg-4">
				<div class="sidebar-widget schedule-widget mt-5">
					<h5 class="mb-4">Time Schedule</h5>

					<ul class="list-unstyled">
					  <li class="d-flex justify-content-between align-items-center">
					    <a href="#">Saturday - Thursday</a>
					    <span>9:00 - 17:00</span>
					  </li>
					  <li class="d-flex justify-content-between align-items-center">
					    <a href="#">Saturday</a>
					    <span>9:00 - 16:00</span>
					  </li>
					  <li class="d-flex justify-content-between align-items-center">
					    <a href="#">Friday</a>
					    <span>Closed</span>
					  </li>
					</ul>

					<div class="sidebar-contatct-info mt-4">
						<p class="mb-0">Need Urgent Help?</p>
						<h3>+23-4565-65768</h3>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>

<!-- footer Start -->
{% endblock %}