amcgh_django/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from CustomAdminPanel import views, HODview

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('homepage.urls')),
                  path('login/', views.showLoginPage, name="login"),
                  path('doLogin/', views.doLogin, name="doLogin"),
                  # path('get_user_details/', views.GetUserDetails, name="GetUserDetails"),
                  path('logout_user/', views.logout_user, name="logout"),
                  path('admin_home/', HODview.admin_home, name="admin_home"),

                  path('add_department/', HODview.add_department, name="add_department"),
                  path('add_department_save/', HODview.add_department_save, name="add_department_save"),

                  path('add_service/', HODview.add_service, name="add_service"),
                  path('add_service_save/', HODview.add_service_save, name="add_service_save"),

                  path('add_doctor', HODview.add_doctor, name="add_doctor"),
                  path('add_doctor_save', HODview.add_doctor_save, name="add_doctor_save"),

                  path('add_mt', HODview.add_mt, name="add_mt"),
                  path('add_mt_save', HODview.add_mt_save, name="add_mt_save"),

                  path('add_gb', HODview.add_gb, name="add_gb"),
                  path('add_gb_save', HODview.add_gb_save, name="add_gb_save"),

                  path('add_gallery', HODview.add_gallery, name="add_gallery"),
                  path('add_gallery_save', HODview.add_gallery_save, name="add_gallery_save"),

                  path('add_category', HODview.add_category, name="add_category"),
                  path('add_category_save', HODview.add_category_save, name="add_category_save"),


                  path('manage_doctor', HODview.manage_doctor, name="manage_doctor"),
                  path('manage_service', HODview.manage_service, name="manage_service"),
                  path('manage_department', HODview.manage_department, name="manage_department"),
                  path('manage_mt', HODview.manage_mt, name="manage_mt"),
                  path('manage_gb', HODview.manage_gb, name="manage_gb"),
                  path('manage_gallery', HODview.manage_gallery, name="manage_gallery"),


                  path('edit_mt/<str:mt_id>', HODview.edit_mt, name="edit_mt"),
                  path('edit_mt_save', HODview.edit_mt_save, name="edit_mt_save"),
                  path('edit_gb/<str:gb_id>', HODview.edit_gb, name="edit_gb"),
                  path('edit_gb_save', HODview.edit_gb_save, name="edit_gb_save"),
                  path('edit_doctor/<str:doctor_id>', HODview.edit_doctor, name="edit_doctor"),
                  path('edit_doctor_save', HODview.edit_doctor_save, name="edit_doctor_save"),
                  path('edit_department/<str:department_id>', HODview.edit_department, name="edit_department"),
                  path('edit_gallery/<str:gallery_id>', HODview.edit_gallery, name="edit_gallery"),
                  path('edit_department_save', HODview.edit_department_save, name="edit_department_save"),
                  path('edit_gallery_save', HODview.edit_gallery_save, name="edit_gallery_save"),

                  # # #     Staff URL Path
                  # path('staff_home', Staffviews.staff_home, name="staff_home"),
                  # path('staff_take_attendence', Staffviews.staff_take_attendence, name="staff_take_attendence"),
                  # path('student_home', Studentviews.student_home, name="student_home")
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL,
                                                                                         document_root=settings.STATIC_ROOT)

homepage/urls.py
from django.conf.urls.static import static

from django.conf import settings
from homepage.views import (home_view,
                            blog_view,
                            about_us_view,
                            service_list_view,
                            doctor_list_view,
                            contact_view,
                            doctor_details,
                            gb_list_view,
                            department_details,
                            management_team_view,
                            service_details_view,
                            gallery_view,backgroundhistory,career,whoweare,missionvission)
from django.urls import path
from . import views

app_name = 'homepage'
urlpatterns = [
                  path('', home_view, name='Home'),
                  # path('department_view/',department_view, name='department'),
                  # path('service/',service_view,name='service'),
                  # path('appointment/', appointment_view, name= 'appointment'),
                  path('contact/', contact_view, name='contact-us'),
                  path('blog/', blog_view, name='blog'),
                  path('about/', about_us_view, name='about'),
                  path('gallery/', gallery_view, name='gallery'),
                  # path('login_user/', views.user_login, name='login'),
                  path('register_user', views.register_view, name='register'),
                  path('service_details/<int:id>', service_details_view, name='service_detail'),
                  path('service-list/', service_list_view, name='service-list'),
                  # path('service-insert/', service_insert_view),
                  # path('news/', views.blog_list_view, name='news'),
                  # path('<int:id>/', views.dynamic_lookup_view, name='news-details'),
                  path('doctor-list/', doctor_list_view, name='doctor-list'),
                  path('department_details/<int:id>/', department_details, name='department_details'),
                  # path('department-list/', department_list_view, name='department-list'),
                  path('doctor_details/<int:id>', doctor_details, name="doctor_details"),
                  path('gb_list/', gb_list_view, name="governing-body"),
                  path('mt_list/', management_team_view, name="management-team"),
                  path('career/', career, name="career"),
                  path('mission&vission/', missionvission, name="mission&vission"),
                  path('whoWeAre/', whoweare, name="whoWeAre"),
                  path('backgroundHistory/', backgroundhistory, name="backgroundHistory"),

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL,
                                                                                         document_root=settings.STATIC_ROOT)

homepage/models.py
# from datetime import datetime
# from django.db import models
# from django.urls import reverse
# from PIL import Image
# from ckeditor.fields import RichTextField
#
#
# class Degree(models.Model):
#     degree_name = models.CharField(max_length=50, null=False)
#
#     def __str__(self):
#         return self.degree_name
#
#
# class Department(models.Model):
#     name = models.CharField(max_length=50)
#     department_image = models.ImageField(upload_to='department_image', default='default.png')
#     short_description = models.CharField(max_length=250, default='Nothing Found')
#     description = models.TextField(blank=False, default='Nothing Found')
#     published = models.DateTimeField(default=datetime.now)
#
#     def __str__(self):
#         return self.name
#
#     def save(self, **kwargs):
#         super().save()
#
#         img = Image.open(self.department_image.path)
#         if img.height > 300 or img.width > 300:
#             output_size = (300, 300)
#             img.thumbnail(output_size)
#             img.save(self.department_image.path)
#
#     def get_absolute_url(self):
#         return reverse("Doctor:department-detail", kwargs={"id": self.id})
#
#
# class Doctor(models.Model):
#     title = models.CharField(max_length=100, blank=False)
#     Designation = models.CharField(blank=False, null=True, max_length=100)
#     doctor_image = models.ImageField(upload_to='doctor_profile_image', default='default.png')
#     Degree = models.ManyToManyField(Degree, blank=False)
#     contact = models.EmailField(max_length=254, blank=False)
#     department = models.ForeignKey(Department, blank=False, null=False, on_delete=models.CASCADE)
#     research_publications = RichTextField(blank=True, null=True)
#     visiting_time = models.CharField(max_length=254, blank=False)
#     published = models.DateTimeField(default=datetime.now)
#
#     def save(self, **kwargs):
#         super().save()
#
#         img = Image.open(self.doctor_image.path)
#         if img.height > 300 or img.width > 300:
#             output_size = (300, 300)
#             img.thumbnail(output_size)
#             img.save(self.doctor_image.path)
#
#     def __str__(self):
#         return self.title
#
#
# # Create your models here.
# class Author(models.Model):
#     name = models.CharField(max_length=30)
#
#     def __str__(self):
#         return self.name
#
#
# class Category(models.Model):
#     name = models.CharField(max_length=20)
#
#     def __str__(self):
#         return self.name
#
#
# class news(models.Model):
#     title = models.CharField(max_length=120)
#     news_image = models.ImageField(upload_to="Newsevents", default='default.png')
#     author = models.ForeignKey(Author, on_delete=models.CASCADE)
#     description = RichTextField(default='No Information Available', blank=False, null=False)
#     categories = models.ManyToManyField(Category)
#     publish_date = models.DateTimeField()
#     views = models.IntegerField(default=0)
#     reviewed = models.BooleanField(default=False)
#
#     def __str__(self):
#         return self.title
#
#     def get_absolute_url(self):
#         return reverse("Newsevents:news-details", kwargs={"id": self.id})
#
#
# class service(models.Model):
#     service_name = models.CharField(max_length=50)
#     service_short_description = models.CharField(max_length=500)
#     service_description = models.TextField(blank=False, null=False)
#     service_image = models.ImageField(upload_to='Service', default='medical_oncology.jpg')
#
#     def get_absolute_url(self):
#         return reverse("Service:service-detail", kwargs={"id": self.id})  # /* dynamic url */
#
#     def __str__(self):
#         return self.service_name

homepage/forms.py
# from django import forms
# from .models import Department, service
# from .models import Doctor
#
# class DoctorForm(forms.ModelForm):
#
#     contact = forms.EmailField()
#
#     class Meta:
#         model = Doctor
#         fields = [
#             'title',
#             'Degree',
#             'Designation',
#             'contact',
#             'department'
#         ]
#
#
# class ServiceForm(forms.ModelForm):
#     class Meta:
#         model = service
#         fields = [
#             'service_name',
#             'service_short_description',
#             'service_description',
#             'service_image'
#         ]
#
#
#
#
# class DepartmentForm(forms.ModelForm):
#
#     class Meta:
#         model= Department
#         fields= [
#             'name',
#             'description',
#             'department_image'
#         ]
#

homepage/views.py
from django.shortcuts import render
from CustomAdminPanel.models import Doctors, Departments, Service, GoverningBody, ManagementTeam, Gallery, \
    GalleryCategory

from django.db.models import Q


def home_view(request):
    department_menu = Departments.objects.all()
    department_home_view = Departments.objects.all()[:2]
    service_home_view = Service.objects.all()[:8]
    doctor_list = Doctors.objects.all()
    context = {
        'service_list': service_home_view,
        'doctor_list': doctor_list,
        'department_list': department_home_view,
        'department_menu': department_menu
    }
    return render(request, 'homepage/index.html', context)


def blog_view(request):
    department_menu = Departments.objects.all()
    context = {
        'department_menu': department_menu
    }
    return render(request, 'News&events/blog-sidebar.html', context)


def about_us_view(request):
    department_menu = Departments.objects.all()
    context = {
        'department_menu': department_menu
    }
    return render(request, 'about.html', context)


def register_view(request):
    department_menu = Departments.objects.all()
    context = {
        'department_menu': department_menu
    }
    return render(request, 'User/register.html', context)


# def doctor_form_view(request):
#     form= DoctorForm()
#     if request.method == "POST":
#         form= DoctorForm(request.POST)
#         if form.is_valid():
#             form.save()
#             return redirect('doctor-insert')
#         else:
#             form = DoctorForm()
#
#     context = {
#         'form': form
#         }
#     return render(request, "Doctors/doc_insert.html", context)


def doctor_details(request, id):
    request.session['doctor_id'] = id
    obj = Doctors.objects.get(admin=id)
    doctor_details = Doctors.objects.all()
    department_menu = Departments.objects.all()
    context = {
        'object': obj,
        'doctor_details': doctor_details,
        'department_menu': department_menu
    }
    return render(request, "Doctors/doctor-single.html", context)


def department_details(request, id):
    request.session['department_id'] = id
    department = Departments.objects.get(id=id)
    doctor_list = Doctors.objects.all()
    department_menu = Departments.objects.all()
    department_list = Departments.objects.all()
    departments = request.GET.get('departments')
    if departments is None:
        pass
    else:
        doctor_list = Doctors.objects.filter(department_id__department_name__icontains=departments)

    context = {
        'doctor_list': doctor_list,
        'department': department,
        'department_list': department_list,
        "id": id,
        'department_menu': department_menu
    }
    return render(request, "Department/department-single.html", context)


def is_valid_queryparam(param):
    return param != '' and param is not None


def doctor_list_view(request, *args, **kwargs):
    department_menu = Departments.objects.all()
    qs = Doctors.objects.all()

    department_list = Departments.objects.values_list('department_name', flat=True)

    name_contains_query = request.GET.get('name_contains')
    print(name_contains_query)

    if is_valid_queryparam(name_contains_query):
        qs = qs.filter(department_id__department_name__contains=name_contains_query)
    else:
        qs = Doctors.objects.all()

    context = {
        'queryset': qs,
        'department_list': department_list,
        'department_menu': department_menu

    }

    return render(request, "Doctors/doctor_list.html", context)


def service_list_view(request):
    department_menu = Departments.objects.all()
    if 'q' in request.GET:
        q = request.GET['q']
        filtered_service_list = Service.objects.filter(service_name__icontains=q)
    else:
        filtered_service_list = Service.objects.all()

    context = {
        's_list': filtered_service_list,
        'department_menu': department_menu
    }
    return render(request, "Services/service.html", context)


def gb_list_view(request):
    department_menu = Departments.objects.all()
    gb = GoverningBody.objects.all()

    context = {
        'gb': gb,
        'department_menu': department_menu
    }
    return render(request, "governing_body.html", context)


def management_team_view(request):
    management_team = ManagementTeam.objects.all()
    department_menu = Departments.objects.all()
    context = {
        'management_team': management_team,
        'department_menu': department_menu
    }
    return render(request, "management_team.html", context)


def service_details_view(request, id):
    service = Service.objects.get(id=id)
    service_details = Service.objects.all()
    department_menu = Departments.objects.all()
    context = {
        'service': service,
        'service_details': service_details,
        'department_menu': department_menu
    }
    return render(request, "Services/service-detail.html", context)


def contact_view(request):
    department_menu = Departments.objects.all()
    context = {
        'department_menu': department_menu
    }
    return render(request, 'contact.html', context)


def gallery_view(request):
    department_menu = Departments.objects.all()
    gallery_category = GalleryCategory.objects.all()
    gallery = Gallery.objects.all()
    filterd_gallery_category = request.GET.get('category')

    if filterd_gallery_category == 'All':
        gallery = Gallery.objects.all()
    elif is_valid_queryparam(filterd_gallery_category):
        gallery = gallery.filter(category_id__category_name=filterd_gallery_category)

    context = {
        'gallery_category': gallery_category,
        'filterd_gallery': gallery,
        'department_menu': department_menu
    }
    return render(request, 'gallary.html', context)


def career(request):
    return render(request, 'career.html')


def missionvission(request):
    return render(request, 'mission&vision.html')


def whoweare(request):
    return render(request, 'whoweare.html')


def backgroundhistory(request):
    return render(request, 'backgroundhistory.html')

homepage/templates/backgroundhistory.html
{% extends 'base.html' %}
{% block title %}Background History | Ahsania Mission Cancer & General Hospital{% endblock title %}
{% block page_name %}Background History{% endblock page_name %}
{% block page_link %}<a href="{% url 'homepage:governing-body' %}">Background History</a>{% endblock page_link %}
{% load static %}
{% block content %}
        <section class="section-padding bg-light-white service-page">
            <div class="container">
                <div class="row">

                   <div class="col-lg-12">
                        <div class="col-12">
                            <div class="service-detail-sec bg-custom-white bx-wrapper">
                                <div class="services-detail-slider mb-xl-30">
                                    <div class="service-image">
                                        <img src="{% static 'assets/images/Banner_2_1920x810.jpg' %}" class="image-fit" alt="department_image">
                                        <div class="overlay overlay-bg-black"></div>
                                        <div class="service-text-wrapper transform-center">
                                            <h3 class="text-custom-white">{{ department.department_name }}</h3>

                                        </div>
                                    </div>

                                </div>
                                <div class="service-meta mb-xl-30">
                                    <p align="justify" class="text-light-white">Dhaka Ahsania Mission (DAM) as part of their long time welfare activities for the people in distress, enthusiastically embarked with a bold initiative to establish a 500-bed world-class cancer hospital in Bangladesh at Sector-10, in Uttara of the capital Dhaka. Compatible spectacular architectural design for the ‘Dream’ Hospital was created by “Design Alliance”, a US based architectural firm. Ahsania Mission Cancer and General Hospital, Uttara started its long awaited journey through its formal inauguration on 9th April’ 2014 by the honorable Prime Minister  Peoples Republic of Bangladesh. Through rigorous situation analysis for Bangladesh on Cancer, from the very beginning the Hospital was  planned as a `State of the Art’ 500 bed advanced hospital with pictureseque architectural beauty situated on the bank of river Turag in the northern part of Dhaka Metropolitan City. This is a13 (thirteen) storied building plus 2 (two) basements having facilities for the treatment of both Cancer & all other patients with an emphasis to cancer treatment.<br><br>

Objectives were set to create establishment for a World Class Treatment and research Center for Cancer and related diseases in Bangladesh within the reach of common people. Ahsania Mission Cancer and General Hospital (AMCGH) had been planned to be a ‘Center of Excellence’ in the country in the field of Cancer control operating in the “State Of Art” mode, continuing to run on ‘NO PROFIT-NO LOSS’ basis and 30% of services alloted cost free or at a subsidized rates to poor and needy patients. As per the set objectives the average costs of treatment in this hospital is considerably less than any other hospitals in private or NGO sectors in Bangladesh or South Asia region for Cancer treatment and related services. It has also strated refraining Bangladeshi cancer patients to travel abroad for “medical tourism” for treatment and thus saving valuable foreign currency.<br><br>

Treatment of cancer and other diseases was started with an advanced LINAC radiotherapy machine from world reputed ELEKTA. UK with CT Simulator, TPS and other required QA tools as per the international protocol in an appropriately specifiedradiation protected vault. Afterwards a latest Brachy therapy machine from ELEKTA Netherlands was  installed for internal radiotherapy and started rendering regular service to the patients. Later a Tele Cobalt machine from world reputed Theratron, Canada was procured and installed. A General Out Patients Department (OPD) was organized to provide service to the health care service seekers with consultants of different disciplines like Gynae & Obstetrics, Medicine & Cardiology, Surgery and Orthopedics etc. Chemotherapy  is continued and with recent advancement in HVAC (Central Air Condition), different patient wards and cabins were commissioned for services at Level 6 and others. Planned full Diagnostics Facilities with Laboratory & Radiology with CR and DR are  installed and now are in working. Three  of the total 11 most advanced Operation Theatres have been  commissioned for surgery, and by time, a number of complicated surgery were conducted. With the completion of major part of  HVAC (Central AC), most of the indoor facilities are organized and completed. Advanced Mamography, Color Dopler 4D Ultrasonogram, latest Echo-Cardiogram, Bone Densitometry (BMD) Machine and OPG machines are installed and started to provide services. Besides this, Day Care, OPD and Pharmacy facilities are there. Response of cancer patients is increasing. The radiotherapy department remains busy with 2 (two) shifts or 3 shifts per day.<br><br>

In last years, medical and other equipments total of worth BDT 130 Crores (approx) were procured, installed or gathered at our Hospital, most of the equipments are already installed, a few are in process of installation.<br><br>

Construction of hospital building is complete. Finishing works of diferent departments, OT, administrative floor and other services are complete. Hope the second phase of development of the hospital is scheduled to be completed by December, 2016. 2nd LINAC machine, Canadian Icon Best Theratronics TeleCobalt Machine,  most advanced MI Spect Dual Head Schintron Gamma Camera, most advanced OT equipments, advanced German WISAP and ther brand Endoscopy and Laparoscopy and others electro-medical equipments are procured and installed.<br><br>

Recently an advanced MRI and CT Scan were procured from reputed Siemens Germany, installed and started services to the patients.

Second LINAC Machine with IMRT, IGRT, VMAT and SRS etc. facilities has been already installed and commissioned for higher precision services to the patientas.
For the Laboratory Diagnostic, advanced and latest for country pathology, immunology……….

In the field of Power/Electricity management for AMCGH, a remarkable success has been achieved, we could successfully negotiate with DESCO and a MOU has been signed with DESCO through which we are presently getting 1.5 MW Electricity temporarily with the existing 0.45 MW and DESCO is constructing a Sub-Station at AMCGH premise to supply us adequately with 5 MW, put by AMCGH to DESCO as our  demand as our total requirement for the Hospital and associates.

The total budget of the hospital is approximately BDT 465 Crores  total expenditure so far is BDT 248 Crores and still we need approximately 217 Crores for eastablishing Medical College, completion of the remaining works for the Hospital and for other medical and other equipments.

Statistically analysis of cancer patients/ no. of cases of last year (July’15 – June’16) at AMCGH, Uttara, Dhaka</p>

                                </div>
                            </div>


                    </div>
                </div>
                </div>
                </div>
        </section>

{% endblock %}



Radiotherapy-LINAC
Radiotherapy-Brachy Therapy
Chemotherapy
Day Care
OPD
Mamography
Ultrasonograpy
Laboratory
Radiology
Pharmacy
OT Service (Limited Scale)
Limited Indoor Service
Limited Emergency Service

homepage/templates/career.html
{% extends 'base.html' %}
{% block title %}Career | Ahsania Mission Cancer & General Hospital{% endblock title %}
{% block page_name %}Career{% endblock page_name %}
{% block page_link %}<a href="{% url 'homepage:governing-body' %}">Career</a>{% endblock page_link %}
{% load static %}
{% block content %}


{% endblock %}

homepage/templates/gallary.html
   {% extends 'base.html' %}
{% block title %}Gallery | Ahsania Mission Cancer & General Hospital{% endblock title %}
{% block page_name %}Gallery{% endblock page_name %}
{% block page_link %}<a href="{% url 'homepage:gallery' %}">Gallery</a>{% endblock page_link %}
{% load static %}
{% block content %}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.13.1/css/bootstrap-select.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

        <section class="section-padding gallery-style-2 style-3">
            <div class="container">
                <div class="section-header">
                    <div class="section-heading">
                        <h3 class="text-custom-black fw-700">Our Gallery</h3>
                        <img src="{% static 'assets/images/title-icon.png' %}" class="mb-xl-20" alt="img">
                        <div class="section-description">
                            <p class="text-light-white">
                                Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text.
                            </p>
                        </div>
                    </div>
                </div>
                <div class="row"  style="padding: 20px;" >
                    <div class="col-8">
                    </div>
                       <div class="col-6">

                           <form class="form-inline">

                    <div class="form-group mx-sm-3 mb-2 select">
                            <select class="form-control" name="category" >
                                <option value="All">All</option>
                                {% for category_list in gallery_category %}
                                    <option value="{{ category_list.category_name }}">{{ category_list.category_name }}</option>
                                {% endfor %}

                            </select>
  </div>
  <button type="submit" class="btn-first btn-submit text-light-blue mb-2">Submit</button>
</form>

                    </div>
                </div>
                <div class="row gallery-grid">
                    {% for gallery_images in filterd_gallery %}
                    <div class="col-lg-4 col-sm-6 filter-box category_name">
                        <div class="gallery-item animate-img mb-xl-30">
                            <a href="{{ gallery_images.gallery_image}}" class="popup">
                                <img src="{{ gallery_images.gallery_image }}" class="image-fit" alt="img">
                            </a>
                        </div>
                    </div>
                    {% endfor %}

                </div>
            </div>
        </section>

<style>
:root {
  --background-gradient: linear-gradient(30deg, #f39c12 30%, #f1c40f);
  --gray: #34495e;
  --darkgray: #2c3e50;
}

select {
  /* Reset Select */
  appearance: none;
  outline: 0;
  border: 0;
  box-shadow: none;
  /* Personalize */
  flex: 1;
  padding: 0 1em;
  color: #fff;
  background-color: #2c3e50;
  background-image: none;
  cursor: pointer;
}
/* Remove IE arrow */
select::-ms-expand {
  display: none;
}
/* Custom Select wrapper */
.select {
  position: relative;
  display: flex;
  width: 20em;
  height: 3em;
  border-radius: .25em;
  overflow: hidden;
}
/* Arrow */

/* Transition */
.select:hover::after {
  color: #f39c12;
}

/* Other styles*/
h1 {
  margin: 0 0 0.25em;
}

</style>

  {% endblock %}

homepage/templates/mission&vision.html
{% extends 'base.html' %}
{% block title %}Mission & Vision | Ahsania Mission Cancer & General Hospital{% endblock title %}
{% block page_name %}Mission & Vision{% endblock page_name %}
{% block page_link %}<a href="{% url 'homepage:governing-body' %}">Mission & Vision</a>{% endblock page_link %}
{% load static %}
{% block content %}

              <section class="section-padding bg-light-white service-page" style="padding-bottom: 0px;">
            <div class="container">
                <div class="row">
                   <div class="col-lg-12">
                        <div class="col-12">
                            <div class="service-detail-sec bg-custom-white bx-wrapper">
                                <div class="services-detail-slider mb-xl-30">
                                    <div class="service-image">
                                        <img src="{% static 'assets/images/mission-vision.jpg' %}" class="image-fit" alt="department_image">
                                    </div>
                                </div>
                            </div>
                    </div>
                </div>
                </div>
                </div>
        </section>
    <section class="section-padding bg-light-white service-page" style="padding-top: 0px;">
            <div class="container">
                <div class="row">
                   <div class="col-lg-6">
                        <div class="col-12">
                            <div class="service-detail-sec bg-custom-white bx-wrapper">
                                <div class="services-detail-slider mb-xl-30">
                                        <h3 align="center" class="text-custom-black">
                                                Mission
                                        </h3>
                                    </div>

                            </div>
                    </div>
                </div>
                   <div class="col-lg-6">
                        <div class="col-12">
                            <div class="service-detail-sec bg-custom-white bx-wrapper">
                                <div class="services-detail-slider mb-xl-30">
                                           <h3 align="center" class="text-custom-black">
                                                Vision
                                        </h3>
                                    </div>

                            </div>
                    </div>
                </div>
                </div>
                </div>
        </section>


{% endblock %}